### PR TITLE
Retry writes to stream on a EAGAIN IOError

### PR DESCRIPTION
**Pull request by morganwahl**
Fixes https://github.com/JetBrains/teamcity-messages/issues/212

Includes regression test.

Normally I'd use a library like https://github.com/rholder/retrying for this, but I wasn't sure if you wanted an extra dependency.

### CODE REVIEW

**Comment by shalupov** [comment]
Thanks! Please tell if it actually fixes your issue

**Comment by morganwahl** [comment]
Will do. When do you expect to make a new release?

**Comment by shalupov** [comment]
Released 1.25

**Comment by morganwahl** [comment]
Cool. We were getting these multiple times a week, so if we go a week with no more of them I'll call it a success. Will update tomorrow.

**Comment by morganwahl** [comment]
FYI, it's been well over a week and no more `IOErrors`.

**Pull request merged**
