### PR TITLE
Implement support for blocks

### PR DESCRIPTION
**Pull request by msabramo**
Implement blocks as described at https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-BlocksofServiceMessages

```
$ tox
...
_________________________________________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________________________________________
  py26: commands succeeded
  py27: commands succeeded
  pypy: commands succeeded
  py32: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  pypy3: commands succeeded
  congratulations :)
```

Cc: @shalupov, @sudarkoff, @aconrad, @djeebus

### CODE REVIEW

**Comment by msabramo** [comment]
Not sure why Travis CI failed -- looks like some intermittent system problem perhaps.

**Comment by msabramo** [comment]
Thanks, @shalupov! Could we get a new release on PyPI perhaps?

**Comment by shalupov** [comment]
done

**Comment by djeebus** [comment]
Thanks for being so responsive!

**Comment by shalupov** [comment]
:)

**Pull request merged**
