### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by sambrightman**
Taking the view that it's better to first get the build green and then
add support for new versions.

### CODE REVIEW

**Comment by sambrightman** [comment]
The Travis error looks like a transient network error that will succeed when retried. I did not look much at AppVeyor - it can't find `pywin32>=223` but it exists https://pypi.org/project/pywin32/#history.

**Comment by sambrightman** [comment]
Hmm, there are no wheels for 3.4. Not sure if they dropped support and what you want to do about that. Still, this fixes the Travis build.

**Comment by sambrightman** [comment]
I added a workaround for Python 3.4 on Windows even though it's EOL soon. Python 2.7 may still fail due to pytest-dev/pytest/issues#4770 coming up in the last few hours.

**Comment by sambrightman** [comment]
All tests should now pass (on re-run of AppVeyor/Python 2.7)

**Comment by shalupov** [comment]
Thanks!

**Pull request merged**
